[package]
name = "horizon"
version = "0.1.0"
edition = "2024"

[lints.rust]
unused = "allow"

[dependencies]
glutin = "0.29.1"
gl = "0.14.0"
thiserror = "2.0.17"
image = "0.25.8"
lazy_static = "1.4.0"